apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: rc-restore
  namespace: demo
spec:
  repository:
    name: local-repo-1
  rules:
  - paths:
    - /source/data
  target: # target indicates where the recovered data will be stored
    ref:
      apiVersion: v1
      kind: ReplicationController
      name: stash-demo
    volumeMounts:
    - name:  source-data
      mountPath:  /source/data
