apiVersion: stash.appscode.com/v1beta1
kind: BackupConfigurationTemplate
metadata:
  name: pvc-backup
spec:
  runtimeSettings:
    pod:
      serviceAccountName: pvc-backup-restore
  backend:
    local:
      mountPath: /safe/data
      hostPath:
        path: /data/stash-test/${TARGET_NAMESPACE}/${TARGET_KIND}/${TARGET_NAME}
    storageSecretName: local-secret
  schedule: "* * * * *"
  task:
    name: pvc-backup
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true

# stash cli backup-pv --namespace demo --template pvc-backup --volume demo-pv --directories /source/data --mountpath /source/data
