apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: update-status-roles
  labels:
    app: stash
rules:
- apiGroups:
  - stash.appscode.com
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - "events"
  verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvc-backup-restore
  namespace: demo
  labels:
    app: stash
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: update-status-binding
  namespace: demo
  labels:
    app: stash
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: update-status-roles
subjects:
- kind: ServiceAccount
  name: pvc-backup-restore
  namespace: demo