apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: mysql-restore-01
  namespace: demo
spec:
  runtimeSettings:
    pod:
      serviceAccountName: mysql-backup-restore
  task:
    name: mysql-restore-task
  repository:
    name: hello-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mysql-quickstart
  rules:
  - snapshots: [latest]
