apiVersion: stash.appscode.com/v1beta1
kind: BackupBatch
metadata:
  name: deploy-backup-batch
  namespace: demo
spec:
  repository:
    name: gcs-repo
  schedule: "*/5 * * * *"
  backupConfigurationTemplates:
  - spec:
      target:
        ref:
          apiVersion: apps/v1
          kind: Deployment
          name: deploy-stash-demo
        volumeMounts:
        - name: source-data
          mountPath: /source/data
        paths:
        - /source/data
  - spec:
      target:
        ref:
          apiVersion: apps/v1
          kind: DaemonSet
          name: dmn-stash-demo
      volumeMounts:
      - name: source-data
        mountPath: /source/data
      paths:
      - /source/data
  - spec:
      target:
        ref:
          apiVersion: apps/v1
          kind: StatefulSet
          name: sts-stash-demo
        volumeMounts:
        - name: source-data
          mountPath: /source/data
        paths:
        - /source/data
  retentionPolicy:
    name: 'keep-last-10'
    keepLast: 10
    prune: true
