apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cross-namespace-target-reader
rules:
  - apiGroups: [""]
    resources: ["secrets","pods","endpoints"]
    verbs: ["get", "list"]
  - apiGroups: ["appcatalog.appscode.com"]
    resources: ["appbindings"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cross-namespace-target-reader
subjects:
  - kind: ServiceAccount
    name: cross-namespace-target-reader
    namespace: backup
roleRef:
  kind: ClusterRole
  name: cross-namespace-target-reader
  apiGroup: rbac.authorization.k8s.io
