apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: quick-postgres
  namespace: demo
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: quick-postgres
    app.kubernetes.io/managed-by: kubedb.com
    app.kubernetes.io/name: postgreses.kubedb.com
spec:
  type: kubedb.com/postgres
  secret:
    name: quick-postgres-auth
  clientConfig:
    service:
      name: quick-postgres
      path: /
      port: 5432
      query: sslmode=disable
      scheme: postgresql
  version: "10.2"
