apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: restore-pvc
  namespace: demo
spec:
  driver: VolumeSnapshotter
  target:
    volumeClaimTemplates:
      - metadata:
          name: source-pvc-1
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "standard"
          resources:
            requests:
              storage: 1Gi
          dataSource:
            kind: VolumeSnapshot
            name: ${CLAIM_NAME}-1560662826
            # name: source-pvc-1-1560662826
            apiGroup: snapshot.storage.k8s.io
      - metadata:
          name: source-pvc-2
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "standard"
          resources:
            requests:
              storage: 1Gi
          dataSource:
            kind: VolumeSnapshot
            name: ${CLAIM_NAME}-1560662826
            # name: source-pvc-2-1560662826
            apiGroup: snapshot.storage.k8s.io