apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: restore-sample-mysql
  namespace: demo
spec:
  task:
    name: mysql-restore-8.0.21
  repository:
    name: gcs-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: restored-mysql
  rules:
  - snapshots: [latest]
