apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: pvc-restore-demo
  namespace: demo
spec:
  runtimeSettings:
    pod:
      serviceAccountName: demo-pvc-sa
  task:
    name: pvc-restore
  repository:
    name: local-repo
  target:
    ref:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: demo-pvc
    volumeMounts:
    - name: demo-pvc
      mountPath: /source/data
  rules:
  - snapshots: [latest]
    paths:
    - /source/data
