apiVersion: stash.appscode.com/v1beta1
kind: Function
metadata:
  name: update-status
spec:
  image: appscodeci/stash:cluster-backup
  args:
    - update-status
    - --namespace=${NAMESPACE=default}
    - --repository=${REPOSITORY_NAME:=}
    - --backup-session=${BACKUP_SESSION:=}
    - --restore-session=${RESTORE_SESSION:=}
    - --output-dir=${outputDir}
    - --enable-status-subresource=${ENABLE_STATUS_SUBRESOURCE:=false}
---
apiVersion: stash.appscode.com/v1beta1
kind: Function
metadata:
  name: cluster-backup
spec:
  image: appscodeci/stash:cluster-backup
  args:
  - backup-cluster
  - --provider=${REPOSITORY_PROVIDER}
  - --bucket=${REPOSITORY_BUCKET:=}
  - --endpoint=${REPOSITORY_ENDPOINT:=}
  - --path=${REPOSITORY_PREFIX:=}
  - --secret-dir=/etc/repository/secret # specified
  - --scratch-dir=/tmp # specified
  - --hostname=${HOSTNAME:=host-0}
  - --sanitize=${sanitize:=false}
  - --retention-keep-last=${RETENTION_KEEP_LAST:=0}
  - --retention-prune=${RETENTION_PRUNE:=false}
  - --output-dir=${outputDir:=}
  - --enable-cache=${ENABLE_CACHE:=true}
  - --max-connections=${MAX_CONNECTIONS:=0}
  #- --metrics-enabled
  #- --metrics-pushgateway-url
  #- --metrics-dir
  #- --metrics-labels
  volumeMounts:
  - name: ${secretVolume}
    mountPath: /etc/repository/secret
