apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-backup
  labels:
    app: stash
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs: ["get","list"]
- apiGroups:
  - stash.appscode.com
  - repositories.stash.appscode.com
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - "events"
  verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-backup
  namespace: demo
  labels:
    app: stash
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-backup
  namespace: demo
  labels:
    app: stash
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cluster-backup
subjects:
- kind: ServiceAccount
  name: cluster-backup
  namespace: demo
