apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: cluster-backup
spec:
  steps:
  - name: cluster-backup
    params:
    - name: outputDir
      value: /tmp/output # specified
    - name: secretVolume
      value: secret-volume # specified
  - name: update-status
    params:
    - name: outputDir
      value: /tmp/output # specified
  volumes:
  - name: secret-volume
    secret:
      secretName: ${REPOSITORY_SECRET_NAME}
