apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: deployment-backup
  namespace: demo
spec:
  repository:
    name: gcs-repo
  schedule: "* * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: stash-demo
    volumeMounts:
      - name: source-data-1
        mountPath: /source/data-1
      - name: source-data-2
        mountPath: /source/data-2
    directories:
      - /source/data-1
      - /source/data-2
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
