apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: restore-pvc
  namespace: demo
spec:
  driver: VolumeSnapshotter
  target:
    replicas : 3
    volumeClaimTemplates:
      - metadata:
          name: source-data-stash-demo
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "standard"
          resources:
            requests:
              storage: 6Gi
          dataSource:
            kind: VolumeSnapshot
#            name: ${CLAIM_NAME}-${POD_ORDINAL}-1560231666
            name: ${CLAIM_NAME}-0-1560231666
#            name: source-data-stash-demo-0-1560231666
            apiGroup: snapshot.storage.k8s.io