apiVersion: v1
kind: Secret
metadata:
  name: local-secret
  namespace: demo
data:
  RESTIC_PASSWORD: bm90QHNlY3JldA==
type: Opaque
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: repo-pvc
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfigurationTemplate
metadata:
  name: workload-backup-template
spec:
  backend:
    local:
      mountPath: /safe/data
      subPath: repo/stash-test/${TARGET_NAMESPACE}/${TARGET_KIND}/${TARGET_NAME}
      persistentVolumeClaim:
        claimName: repo-pvc
    storageSecretName: local-secret
  schedule: "* * * * *"
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
