apiVersion: v1
kind: Secret
metadata:
  name: local-secret
  namespace: demo
data:
  RESTIC_PASSWORD: bm90QHNlY3JldA==
type: Opaque
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: repo-pvc
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: local-repo
  namespace: demo
spec:
  backend:
    local:
      mountPath: /safe/data
      persistentVolumeClaim:
        claimName: repo-pvc
    storageSecretName: local-secret
