apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: stash-demo
  namespace: demo
spec:
  selector:
    matchLabels:
      app: stash-demo
  # type: offline
  fileGroups:
  - path: /source/data
    retentionPolicyName: keep-last-5
  backend:
    local:
      mountPath: /safe/data
      hostPath:
        path: /data/stash-test/restic-repo
    storageSecretName: local-secret
  schedule: '@every 1m'
  # paused: false
  volumeMounts:
  - mountPath: /source/data
    name: source-data
  retentionPolicies:
  - name: keep-last-5
    keepLast: 5
    prune: true
