apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: namespace-resource-storage
  namespace: demo
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: /manifests/namespace/kube-system
    storageSecretName: gcs-secret
