kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc-source
  namespace: demo
  annotations:
    stash.appscode.com/backup-template: pvc-backup
    stash.appscode.com/target-directories: "/source/data"
    stash.appscode.com/mountpath: "/source/data"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256M
