kind: PersistentVolume
apiVersion: v1
metadata:
  name: test-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc-source
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256M
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc-dest
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256M