apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: hello-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: hello-bucket
      prefix: hello-prefix
    storageSecretName: gcs-secret