apiVersion: v1
kind: Pod
metadata:
  name: restored-pod
  namespace: demo
spec:
  containers:
    - name: busybox
      image: busybox
      args:
        - sleep
        - "3600"
      volumeMounts:
        - name: source-data
          mountPath: /demo/data
  volumes:
    - name: source-data
      persistentVolumeClaim:
        claimName: source-pvc
        readOnly: false