apiVersion: v1
kind: Pod
metadata:
  name: source-pod
  namespace: demo
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["touch /demo/data/sample-file.txt && sleep 3000"]
      volumeMounts:
        - name: source-data
          mountPath: /demo/data
  volumes:
    - name: source-data
      persistentVolumeClaim:
        claimName: source-pvc
        readOnly: false