apiVersion: stash.appscode.com/v1beta1
kind: RestoreBatch
metadata:
  creationTimestamp: "2020-07-25T17:41:52Z"
  finalizers:
  - stash.appscode.com
  generation: 1
  managedFields:
  - apiVersion: stash.appscode.com/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:driver: {}
        f:executionOrder: {}
        f:members: {}
        f:repository:
          .: {}
          f:name: {}
    manager: e2e.test
    operation: Update
    time: "2020-07-25T17:41:52Z"
  - apiVersion: stash.appscode.com/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers: {}
      f:status:
        .: {}
        f:conditions: {}
        f:members: {}
        f:phase: {}
        f:sessionDuration: {}
    manager: stash-enterprise
    operation: Update
    time: "2020-07-25T17:42:07Z"
  name: stash-e2e-agnhco-4ol2kh
  namespace: test-stash-i7bq6x
  resourceVersion: "21536"
  selfLink: /apis/stash.appscode.com/v1beta1/namespaces/test-stash-i7bq6x/restorebatches/stash-e2e-agnhco-4ol2kh
  uid: 68729409-bf4a-4edf-a8f3-ef4e63121591
spec:
  driver: Restic
  executionOrder: Parallel
  members:
  - runtimeSettings: {}
    target:
      alias: stash-e2e-agnhco-dpl
      ref:
        apiVersion: apps/v1
        kind: Deployment
        name: source-dp-stash-e2e-agnhco-4ngew4
      rules:
      - paths:
        - /source/data
      volumeMounts:
      - mountPath: /source/data
        name: source-volume
    task:
      name: ""
    tempDir: {}
  - runtimeSettings: {}
    target:
      alias: stash-e2e-agnhco-pvc
      ref:
        apiVersion: v1
        kind: PersistentVolumeClaim
        name: source-pvc-stash-e2e-agnhco
      rules:
      - snapshots:
        - latest
    task:
      name: pvc-restore
    tempDir: {}
  - runtimeSettings: {}
    target:
      alias: stash-e2e-agnhco-db
      ref:
        apiVersion: appcatalog.appscode.com/v1alpha1
        kind: AppBinding
        name: source-mysql-stash-e2e-agnhco
      rules:
      - snapshots:
        - latest
    task:
      name: mysql-restore-8.0.14
    tempDir: {}
  repository:
    name: minio-stash-e2e-agnhco-ajg3eh
status:
  conditions:
  - lastTransitionTime: "2020-07-25T17:41:52Z"
    message: Repository test-stash-i7bq6x/minio-stash-e2e-agnhco-ajg3eh exist.
    reason: RepositoryAvailable
    status: "True"
    type: RepositoryFound
  - lastTransitionTime: "2020-07-25T17:41:52Z"
    message: Backend Secret test-stash-i7bq6x/stash-e2e-agnhco-minio-fl3a53 exist.
    reason: BackendSecretAvailable
    status: "True"
    type: BackendSecretFound
  - lastTransitionTime: "2020-07-25T17:41:52Z"
    message: Successfully created restore job.
    reason: RestoreJobCreationSucceeded
    status: "True"
    type: RestoreJobCreated
  members:
  - conditions:
    - lastTransitionTime: "2020-07-25T17:41:52Z"
      message: Restore target apps/v1 deployment/source-dp-stash-e2e-agnhco-4ngew4
        found.
      reason: TargetAvailable
      status: "True"
      type: RestoreTargetFound
    - lastTransitionTime: "2020-07-25T17:41:52Z"
      message: Successfully injected stash init-container.
      reason: InitContainerInjectionSucceeded
      status: "True"
      type: StashInitContainerInjected
    phase: Succeeded
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: source-dp-stash-e2e-agnhco-4ngew4
    stats:
    - duration: 822.861322ms
      hostname: stash-e2e-agnhco-dpl
      phase: Succeeded
    totalHosts: 1
  - conditions:
    - lastTransitionTime: "2020-07-25T17:41:52Z"
      message: Restore target v1 persistentvolumeclaim/source-pvc-stash-e2e-agnhco
        found.
      reason: TargetAvailable
      status: "True"
      type: RestoreTargetFound
    phase: Succeeded
    ref:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: source-pvc-stash-e2e-agnhco
    stats:
    - duration: 945.948671ms
      hostname: stash-e2e-agnhco-pvc
      phase: Succeeded
    totalHosts: 1
  - conditions:
    - lastTransitionTime: "2020-07-25T17:41:52Z"
      message: Restore target appcatalog.appscode.com/v1alpha1 appbinding/source-mysql-stash-e2e-agnhco
        found.
      reason: TargetAvailable
      status: "True"
      type: RestoreTargetFound
    phase: Succeeded
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: source-mysql-stash-e2e-agnhco
    stats:
    - duration: 4.597812876s
      hostname: stash-e2e-agnhco-db
      phase: Succeeded
    totalHosts: 1
  phase: Succeeded
  sessionDuration: 15.145032437s
