apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongo-backup-restore
  labels:
    app: stash
rules:
- apiGroups:
  - stash.appscode.com
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - appcatalog.appscode.com
  resources:
  - "appbindings"
  verbs: ["get"]
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-backup-restore
  namespace: demo
  labels:
    app: stash
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongo-backup-restore
  namespace: demo
  labels:
    app: stash
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: mongo-backup-restore
subjects:
- kind: ServiceAccount
  name: mongo-backup-restore
  namespace: demo