apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: sample-nats-backup
  namespace: demo
spec:
  schedule: "*/5 * * * *"
  task:
    name: nats-backup-2.6.1
    params:
    - name: args
      value: --check
  repository:
    name: gcs-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: sample-nats
  retentionPolicy:
    name: keep-last-5
    keepLast: 5
    prune: true
