apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: restored-xtradb-restore
  namespace: demo
spec:
  task:
    name: perconaxtradb-restore-5.7.0
  repository:
    name: gcs-repo-sample-xtradb
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: restored-xtradb
  rules:
  - snapshots: ["latest"]
