apiVersion: stash.appscode.com/v1beta1
kind: BackupBatch
metadata:
  name: deploy-backup-batch
  namespace: demo
spec:
  repository:
    name: gcs-repo
  schedule: "*/6 * * * *"
  driver: VolumeSnapshotter
  backupConfigurationTemplates:
    - spec:
        target:
          ref:
            apiVersion: apps/v1
            kind: Deployment
            name: stash-demo
          snapshotClassName: csi-hostpath-snapclass
    - spec:
        target:
          ref:
            apiVersion: apps/v1
            kind: StatefulSet
            name: stash-demo
          replicas : 3
          snapshotClassName: csi-hostpath-snapclass
    - spec:
        target:
          ref:
            apiVersion: v1
            kind: PersistentVolumeClaim
            name: source-data
          snapshotClassName: default-snapshot-class
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
