apiVersion: v1
kind: Pod
metadata:
  name: source-pod
  namespace: demo
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["echo sample_data > /source/data/data.txt && sleep 3000"]
      volumeMounts:
        - name: source-data
          mountPath: /source/data
  volumes:
    - name: source-data
      persistentVolumeClaim:
        claimName: source-data
        readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: source-data
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
