apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: restore
  namespace: demo
spec:
  driver: VolumeSnapshotter
  target:
#    replicas : 3    #for Statefulset
    volumeClaimTemplates:
      - metadata:
          name: pvc
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "standard"
          resources:
            requests:
              storage: 6Gi
          dataSource:
            kind: VolumeSnapshot
#            name: ${CLAIM_NAME}-${POD_ORDINAL}-1558421829    #for Statefulset
            name: ${CLAIM_NAME}-1558421829
            apiGroup: snapshot.storage.k8s.io