apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: pg-backup-config
  namespace: demo
spec:
  runtimeSettings:
    pod:
      serviceAccountName: pg-backup-restore
  schedule: "* * * * *"
  task:
    name: pg-backup-task
  repository:
    name: hello-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: quick-postgres
  retentionPolicy:
    keepLast: 5
    prune: true
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupSession
metadata:
  name: pg-backup-01
  namespace: demo
spec:
  backupConfiguration:
    name: pg-backup-config