apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: pg-backup-task
spec:
  steps:
  - name: pg-backup
    params:
    - name: outputDir
      value: /tmp/output # specified
    - name: secretVolume
      value: secret-volume # specified
  - name: update-status
    params:
    - name: outputDir
      value: /tmp/output # specified
  volumes:
  - name: secret-volume
    secret:
      secretName: ${REPOSITORY_SECRET_NAME}
---
apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: pg-restore-task
spec:
  steps:
  - name: pg-restore
    params:
    - name: outputDir
      value: /tmp/output # specified
    - name: secretVolume
      value: secret-volume # specified
  - name: update-status
    params:
    - name: outputDir
      value: /tmp/output # specified
  volumes:
  - name: secret-volume
    secret:
      secretName: ${REPOSITORY_SECRET_NAME}