apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: pvc-backup-task
spec:
  steps:
  - name: pvc-backup
    params:
    - name: outputDir
      value: /tmp/output # specified
    - name: targetVolume
      value: target-volume # specified
    - name: secretVolume
      value: secret-volume # specified
  - name: update-status
    params:
    - name: outputDir
      value: /tmp/output # specified
  volumes:
  - name: target-volume
    persistentVolumeClaim:
      claimName: ${TARGET_NAME}
  - name: secret-volume
    secret:
      secretName: ${REPOSITORY_SECRET_NAME}
---
apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: pvc-restore-task
spec:
  steps:
  - name: pvc-restore
    params:
    - name: outputDir
      value: /tmp/output # specified
    - name: targetVolume
      value: target-volume # specified
    - name: secretVolume
      value: secret-volume # specified
  - name: update-status
    params:
    - name: outputDir
      value: /tmp/output # specified
  volumes:
  - name: target-volume
    persistentVolumeClaim:
      claimName: ${TARGET_NAME}
  - name: secret-volume
    secret:
      secretName: ${REPOSITORY_SECRET_NAME}
