kind: Pod
apiVersion: v1
metadata:
  name: test-write-soruce
  namespace: demo
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh","-c"]
    args:
    - 'set -x; rm -r /etc/target/*; mkdir /etc/target/dir-01; mkdir /etc/target/dir-02; ls /etc/target'
    volumeMounts:
    - mountPath: /etc/target
      name: test-pvc-source
  restartPolicy: Never
  volumes:
  - name: test-pvc-source
    persistentVolumeClaim:
     claimName: test-pvc-source
