apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  labels:
    app.kubernetes.io/instance: sample-nats
  name: sample-nats
  namespace: demo
spec:
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4VENDQWRtZ0F3SUJBZ0lSQUptTUdvMzUyNHZHdWo4SkRVR05WUVl3RFFZSktvWklodmNOQVFFTEJRQXcKRWpFUU1BNEdBMVVFQXhNSGJtRjBjeTFqWVRBZUZ3MHlNVEE1TVRBeE1ETTNNamxhRncweU1qQTVNRGt4TURNMwpNamxhTUJJeEVEQU9CZ05WQkFNVEIyNWhkSE10WTJFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFEbjNDanFBaE94MG5SbGYrYmJaZXRQenJwSGFkOUdBUS9aa3ZHd2drMWFuY1hwclplVkZjaUYKTVJ5d0IvL3pvdXZGNm9WVTV5NXNlbzRoOU5CQ3NHRzFrRFU3Q1M3Q3dvaGhCNXR5MHBjb2xEaVhCVUVBQXVVMwpIL3ZEV0pGY04wdmpGbnFndWk3ZjFuOVluQzY4aGU1cTczYVdzNnArbEVuMVZOR2dZeHl6c1JUbTdCK2htV045CmJrSzFOd0JaNWN5b3dpVkl0UE5ES3ZRQ2lrT1hrNUZPMGxBL0FSRlA3K01mNFNleXBHM3Z6c2ZnR3k4eEZ2R08KRnJpUDI1VXUvTmNBREdnRW92SDBJWUpSd1VpZkJRVHUvbTAzVytmaVA1eWxQcEUxMVJvOXlFZk45cEd5T2RsYgp6R0xXRGZsNGh3OEhzdXQ2UW1zUTdNczg1c0pZLzBRVkFnTUJBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lDCnBEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCUWVYWndJazdlaTFqOVdseFQ2MkltUkkxbVAKWlRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWw1WmFjWjhKVXNQWGNpU1hEU0U2OG4zR0VPSDl6UExYZUk3MQpnSk4rZjNWTXZzNVUzR3FjdGkvbjR6bXNIU3dDOUU4SDB4RmM4VnR0d2xRTEgrOWtwRnpMcHBaeEVYYXNtOEhhCi93SDdISzF4NEIzeEw3Tk9QemM3YVFKaVZ0S2pMSmNkQW95VGZwWGFnY2dya05OVWVUaUNucXpWUXcyLzFudzgKMWxMYWRpUXJPK0RHck5qcUxUYXB0RVR2anJwczhIMjlFWGJaZmhFWUhDRGtLd2pYMWdNSGJXNXEwWWFyWDFRNQpCTGplb3JVZEZkWTBzNytKeVlUWTRkcGhYTmdJeHMzdWFBdTdMWjMxUVRsd0RRZk5KWVV2cGtaa2RDemVwWDF6Cmo3NVI4Z3lUWno0WEdoTS8wdHFrU3JyWWMwWjU1QTdFR3h1dUg0Si9FcGRrMHJJcnV3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: sample-nats
      port: 4222
      scheme: nats
  secret:
    name: sample-nats-auth
  type: stash/nats
  version: 2.4.0
