name: CI

on:
  push:
    branches-ignore:
      - 'release-*'
    tags-ignore:
      - '*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Install link checker
      env:
        GO111MODULE: on
      run: |
        export GOPATH=$(go env GOPATH)
        export GOBIN=$GOPATH/bin
        mkdir -p $GOBIN
        mkdir -p $GOPATH/github.com/raviqqe
        pushd $GOPATH/github.com/raviqqe
        git clone https://github.com/appscodelabs/liche
        cd liche
        git checkout ignore-private-hosts
        go install -v ./...
        sudo mv $GOBIN/* /usr/local/bin
        popd

    - name: Check links
      run: |
        liche -r docs -d $(pwd) -c 10 -p -x '^'"$(pwd)"'/docs/addons/.*/guides/.*$'
